### ISSUE TITLE
ClassNotFoundException crash after upgrading to v26

### ISSUE THREAD

**Issue by davidmigloz** [Anyline/anyline-ocr-examples-android#11]
Hi team,

I was trying to update the AnyLine SDK from version 23 to 26.1, but now I'm getting the following crash:

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.xxx/com.xxx.core.app.cards.SingleCardHolderActivity}: android.view.InflateException: Binary XML file line #12 in com.xxx:layout/fragment_xxx_scanner: Binary XML file line #12 in com.xxx:layout/fragment_xxx_scanner: Error inflating class io.anyline.view.ScanView
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4444)
       ...
Caused by android.view.InflateException: Binary XML file line #12 in com.xxx:layout/fragment_xxx_scanner: Binary XML file line #12 in com.xxx:layout/fragment_xxx_scanner: Error inflating class io.anyline.view.ScanView
Caused by java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/util/concurrent/MoreExecutors;
       at io.anyline.view.ScanView.<init>(SourceFile:20)
       at io.anyline.view.ScanView.<init>(SourceFile:2)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:852)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
       at com.xxx.databinding.FragmentScannerBinding.inflate(FragmentScannerBinding.java:53)
       at com.xxx.scanner.ScannerFragment.onCreateView(ScannerFragment.kt:69)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
       ...
Caused by java.lang.ClassNotFoundException: Didn't find class "com.google.common.util.concurrent.MoreExecutors" on path: DexPathList[[zip file "/data/app/~~UghjyNcsgtnaIKSZoXs34g==/com.xxx-ZtmsdwXgjyyXx4C5o7TWUQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~UghjyNcsgtnaIKSZoXs34g==/com.xxx-ZtmsdwXgjyyXx4C5o7TWUQ==/lib/arm64, /data/app/~~UghjyNcsgtnaIKSZoXs34g==/com.xxx-ZtmsdwXgjyyXx4C5o7TWUQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at io.anyline.view.ScanView.<init>(SourceFile:20)
       at io.anyline.view.ScanView.<init>(SourceFile:2)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:852)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
       at com.xxx.databinding.FragmentScannerBinding.inflate(FragmentScannerBinding.java:53)
       at com.xxx.scanner.ScannerFragment.onCreateView(ScannerFragment.kt:69)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
       ...
```

These are the changes that I've done:
![image](https://user-images.githubusercontent.com/6546265/100215709-a4c11980-2f11-11eb-9e2a-8e0b360940d4.png)
![image](https://user-images.githubusercontent.com/6546265/100215614-7fcca680-2f11-11eb-8024-989fea6f072f.png)
![image](https://user-images.githubusercontent.com/6546265/100215643-88bd7800-2f11-11eb-9dfa-9f23a4150c5e.png)

any idea?

**Comment by lore-any** [comment]
Dear @davidmigloz ,
Here is Lorena from Anyline.
Please make sure that you implement the Anyline SDK in the following way i nyour build gradle:
**_implementation 'io.anyline:anylinesdk:26'_**

The aar extension should not be present anymore while you import Anyline SDK in your project.

**Comment by davidmigloz** [comment]
Thank you, that was it.

However, now I'm getting dependencies resolution errors:
```
Duplicate class com.google.android.gms.internal.vision.zzbl found in modules jetified-firebase-ml-vision-face-model-17.0.2-runtime (com.google.firebase:firebase-ml-vision-face-model:17.0.2) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zze found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
...
```

I see that you have two conflicting dependencies:
```
+--- io.anyline:anylinesdk:26.1
|    +--- com.google.firebase:firebase-ml-vision:19.0.2
|    |    \--- com.google.android.gms:play-services-vision-common:19.0.2
|    +--- com.google.firebase:firebase-ml-vision-face-model:17.0.2
|    |    \--- com.google.android.gms:play-services-vision-common:17.0.2
```

`firebase-ml-vision-face-model` is also deprecated.

I'll force the resolution to `play-services-vision-common:19.0.2` for now.

As a side note, it would be nice to make the SDK more modular, it's becoming a big and scary monolithic SDK.
Why do I need to depend on a face recognition model if I don't use that feature at all?

**Comment by lore-any** [comment]
Thank you @davidmigloz. We have in plan to continuously improve our SDK, so the developers will have a very smooth experience while integrating Anyline.

Therefore, thank you very much for your valuable feedback. We will make sure that this will be integrated in our improvement process in the new future!

**Comment by davidmigloz** [comment]
Thanks Lorena, glad to hear 🙂

Shall I close this issue? 
Or do you want to keep it open for the conflicting dependencies?

**Comment by lore-any** [comment]
Hi David, 

Please let it open. I will make sure that I will come back to you with updates once we solve internally this issue. 

Thank you,
Lorena K.

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
